### ISSUE TITLE
Choosing Colour Palette for the Frontend

### ISSUE THREAD

**Issue by Nouran246** [Nouran246/Personalized-Recipe-Recommender#7]

**Comment by a-elhaag** [comment]
Here is the link to the color palette and the fonts we'll be using for the frontend: [Color Palette Link](https://www.realtimecolors.com/?colors=697e91-f2f6fa-ffc29e-efce7a-9e7bc2&fonts=Caveat%20Brush-Raleway)

```
--text-50: #f0f2f4;
--text-100: #e1e6ea;
--text-200: #c4cdd4;
--text-300: #a6b3bf;
--text-400: #899aa9;
--text-500: #6b8194;
--text-600: #566776;
--text-700: #404d59;
--text-800: #2b343b;
--text-900: #151a1e;
--text-950: #0b0d0f;

--background-50: #edf2f8;
--background-100: #dae6f1;
--background-200: #b6cce2;
--background-300: #91b2d4;
--background-400: #6c99c6;
--background-500: #477fb8;
--background-600: #396693;
--background-700: #2b4c6e;
--background-800: #1d3349;
--background-900: #0e1925;
--background-950: #070d12;

--primary-50: #ffefe5;
--primary-100: #ffdfcc;
--primary-200: #ffbe99;
--primary-300: #ff9e66;
--primary-400: #ff7e33;
--primary-500: #ff5e00;
--primary-600: #cc4b00;
--primary-700: #993800;
--primary-800: #662500;
--primary-900: #331300;
--primary-950: #1a0900;

--secondary-50: #fcf7e8;
--secondary-100: #faeed1;
--secondary-200: #f4dda4;
--secondary-300: #efcd76;
--secondary-400: #eabc48;
--secondary-500: #e4ab1b;
--secondary-600: #b78915;
--secondary-700: #896710;
--secondary-800: #5b440b;
--secondary-900: #2e2205;
--secondary-950: #171103;

--accent-50: #f2eef7;
--accent-100: #e6dcef;
--accent-200: #ccb9df;
--accent-300: #b296cf;
--accent-400: #9973bf;
--accent-500: #7f50af;
--accent-600: #66408c;
--accent-700: #4c3069;
--accent-800: #332046;
--accent-900: #191023;
--accent-950: #0d0811;
```

and for the fonts 
```css
@import url('https://fonts.googleapis.com/css?family=Caveat%20Brush:700|Raleway:400');

body {
  font-family: 'Raleway';
  font-weight: 400;
}

h1, h2, h3, h4, h5 {
  font-family: 'Caveat Brush';
  font-weight: 700;
}

html {font-size: 100%;} /* 16px */

h1 {font-size: 4.210rem; /* 67.36px */}

h2 {font-size: 3.158rem; /* 50.56px */}

h3 {font-size: 2.369rem; /* 37.92px */}

h4 {font-size: 1.777rem; /* 28.48px */}

h5 {font-size: 1.333rem; /* 21.28px */}

small {font-size: 0.750rem; /* 12px */}
```
